[package]
name = "pokerrust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
poker = "0.4"
serde = "1.0.158"
itertools = "0.10.5"